version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myblog
    networks:
      blog-api:

  springboot-restful-webservices:
    container_name: my-blog-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      blog-api:
    restart: on-failure
networks:
  blog-api: